// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4jwyLOVlIgEzAyQxrQ3w_-KnQTquO9J4',
    appId: '1:247891651415:web:0ac2eee4658df9b2426c12',
    messagingSenderId: '247891651415',
    projectId: 'clone-1c2e9',
    authDomain: 'clone-1c2e9.firebaseapp.com',
    storageBucket: 'clone-1c2e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5PlylMWOQOLSrwpv5Ej0MQKveBmvw1Cw',
    appId: '1:247891651415:android:8cce3fcb0bc8e371426c12',
    messagingSenderId: '247891651415',
    projectId: 'clone-1c2e9',
    storageBucket: 'clone-1c2e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxXZ57nB_uOZ9XTuQq3vvESQQpb1YqWek',
    appId: '1:247891651415:ios:060657d5a8f271e9426c12',
    messagingSenderId: '247891651415',
    projectId: 'clone-1c2e9',
    storageBucket: 'clone-1c2e9.appspot.com',
    iosBundleId: 'com.example.youtubeClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxXZ57nB_uOZ9XTuQq3vvESQQpb1YqWek',
    appId: '1:247891651415:ios:060657d5a8f271e9426c12',
    messagingSenderId: '247891651415',
    projectId: 'clone-1c2e9',
    storageBucket: 'clone-1c2e9.appspot.com',
    iosBundleId: 'com.example.youtubeClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4jwyLOVlIgEzAyQxrQ3w_-KnQTquO9J4',
    appId: '1:247891651415:web:707feecabe177bad426c12',
    messagingSenderId: '247891651415',
    projectId: 'clone-1c2e9',
    authDomain: 'clone-1c2e9.firebaseapp.com',
    storageBucket: 'clone-1c2e9.appspot.com',
  );
}
